## benchmark header info
id: spatial_variable_genes_benchmark
description: Benchmark for evaluating spatially variable gene detection methods on spatial transcriptomics data
version: 1.0
benchmarker: "Aidan Meara"
storage_api: S3
## S3 endpoint to share our benchmark results.
storage: https://s3_object_storage_url.ch
benchmark_yaml_spec: 0.01
software_backend: apptainer

## Software environment recipes associated to this benchmark.
##  These are apptainer .sif images converted from OpenProblems Docker containers
software_environments:
  python_base:
    description: "Python base environment with anndata for data loading"
    apptainer: envs/python_base.sif
  boostgp:
    description: "BOOST-GP method environment"
    apptainer: envs/boostgp.sif
  random_ranking:
    description: "Random ranking control method"
    apptainer: envs/random_ranking.sif
  true_ranking:
    description: "True ranking control method"
    apptainer: envs/true_ranking.sif
  correlation:
    description: "Correlation metric environment"
    apptainer: envs/correlation.sif
  ## TODO: Uncomment when sif files are ready
  # gpcounts:
  #   description: "GPcounts method environment"
  #   apptainer: envs/gpcounts.sif
  # moran_i:
  #   description: "Moran's I method environment"
  #   apptainer: envs/moran_i.sif
  # nnsvg:
  #   description: "nnSVG method environment"
  #   apptainer: envs/nnsvg.sif
  # scgco:
  #   description: "scGCO method environment"
  #   apptainer: envs/scgco.sif
  # sepal:
  #   description: "Sepal method environment"
  #   apptainer: envs/sepal.sif
  # somde:
  #   description: "SomDE method environment"
  #   apptainer: envs/somde.sif
  # spagcn:
  #   description: "SpaGCN method environment"
  #   apptainer: envs/spagcn.sif
  # spagft:
  #   description: "SpaGFT method environment"
  #   apptainer: envs/spagft.sif
  # spanve:
  #   description: "SPANVE method environment"
  #   apptainer: envs/spanve.sif
  # spark:
  #   description: "SPARK method environment"
  #   apptainer: envs/spark.sif
  spark_x:
    description: "SPARK-X method environment"
    apptainer: envs/spark_x.sif
  # spatialde:
  #   description: "SpatialDE method environment"
  #   apptainer: envs/spatialde.sif
  # spatialde2:
  #   description: "SpatialDE2 method environment"
  #   apptainer: envs/spatialde2.sif

## Metric collectors - aggregate scores from all metrics, methods, and datasets
metric_collectors:
  - id: scoring
    name: "Score Aggregation"
    software_environment: "python_base"
    repository:
      url: https://github.com/A-meara/metric_collector_SVG
      commit: 8c5998f
    inputs:
      - metrics.scores
    outputs:
      - id: scoring.csv
        path: "{input}/{name}/aggregated_scores.csv"

stages:
  ## Data stage - loads spatial transcriptomics datasets
  - id: data
    modules:
      ## Mouse datasets
      - id: spatial_variable_genes
        name: "Mouse Brain Coronal Section 1"
        software_environment: "python_base"
        repository:
          url: https://github.com/A-meara/spatially_variable_genes
          commit: 2f93124
        parameters:
          - values: ["--component", "data_loader", "--dataset_id", "spatial_10x_visium/mouse_brain_coronal_section1"]

      ## TODO: Uncomment additional datasets when ready to scale up
      # - id: mouse_olfactory_bulb
      #   name: "Mouse Olfactory Bulb"
      #   software_environment: "python_base"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/data_loader
      #     commit: 2f93124

      #   parameters:
      #     dataset_id: spatial_10x_visium/mouse_olfactory_bulb

      # - id: mouse_embryo
      #   name: "Mouse Embryo"
      #   software_environment: "python_base"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/data_loader
      #     commit: 2f93124

      #   parameters:
      #     dataset_id: spatial_10x_visium/mouse_embryo

      # ## Human datasets
      # - id: human_brain_cancer
      #   name: "Human Brain Cancer"
      #   software_environment: "python_base"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/data_loader
      #     commit: 2f93124

      #   parameters:
      #     dataset_id: spatial_10x_visium/human_brain_cancer

      # - id: human_heart
      #   name: "Human Heart"
      #   software_environment: "python_base"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/data_loader
      #     commit: 2f93124

      #   parameters:
      #     dataset_id: spatial_10x_visium/human_heart

      # - id: human_breast_cancer_1
      #   name: "Human Breast Cancer 1"
      #   software_environment: "python_base"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/data_loader
      #     commit: 2f93124

      #   parameters:
      #     dataset_id: spatial_10x_visium/human_breast_cancer_1

    ## Data stage outputs
    outputs:
      - id: data.dataset
        path: "dataset.h5ad"
      - id: data.solution
        path: "solution.h5ad"

  ## Methods stage - SVG detection methods
  - id: methods
    modules:
      ## Control methods
      - id: random_ranking
        name: "Random Ranking"
        software_environment: "random_ranking"
        repository:
          url: https://github.com/A-meara/spatially_variable_genes
          commit: 2f93124
        parameters:
          - values: ["--component", "methods/random_ranking", "--seed", "42"]

      - id: true_ranking
        name: "True Ranking"
        software_environment: "true_ranking"
        repository:
          url: https://github.com/A-meara/spatially_variable_genes
          commit: 2f93124
        parameters:
          - values: ["--component", "methods/true_ranking"]

      ## R-based methods
      - id: boostgp
        name: "BOOST-GP"
        software_environment: "boostgp"
        repository:
          url: https://github.com/A-meara/spatially_variable_genes
          commit: 2f93124
        parameters:
          - values: ["--component", "methods/boostgp", "--n_iter", "10"]

      # - id: nnsvg
      #   name: "nnSVG"
      #   software_environment: "nnsvg"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/methods/nnsvg
      #     commit: 2f93124


      # - id: spark
      #   name: "SPARK"
      #   software_environment: "spark"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/methods/spark
      #     commit: 2f93124


      - id: spark_x
        name: "SPARK-X" 
        software_environment: "spark_x"
        repository:
          url: https://github.com/A-meara/spatially_variable_genes
          commit: 2f93124
        parameters:
          - values: ["--component", "methods/spark_x", "--num_cores", "4"]

      ## TODO: Uncomment additional methods when sif files are ready
      # ## Python-based methods
      # - id: gpcounts
      #   name: "GPcounts"
      #   software_environment: "gpcounts"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/methods/gpcounts
      #     commit: 2f93124


      # - id: moran_i
      #   name: "Moran's I"
      #   software_environment: "moran_i"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/methods/moran_i
      #     commit: 2f93124

      #   parameters:
      #     coord_type: generic

      # - id: scgco
      #   name: "scGCO"
      #   software_environment: "scgco"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/methods/scgco
      #     commit: 2f93124


      # - id: sepal
      #   name: "Sepal"
      #   software_environment: "sepal"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/methods/sepal
      #     commit: 2f93124

      #   parameters:
      #     coord_type: generic
      #     max_neighs: 6

      # - id: somde
      #   name: "SomDE"
      #   software_environment: "somde"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/methods/somde
      #     commit: 2f93124


      # - id: spagcn
      #   name: "SpaGCN"
      #   software_environment: "spagcn"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/methods/spagcn
      #     commit: 2f93124


      # - id: spagft
      #   name: "SpaGFT"
      #   software_environment: "spagft"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/methods/spagft
      #     commit: 2f93124


      # - id: spanve
      #   name: "SPANVE"
      #   software_environment: "spanve"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/methods/spanve
      #     commit: 2f93124


      # - id: spatialde
      #   name: "SpatialDE"
      #   software_environment: "spatialde"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/methods/spatialde
      #     commit: 2f93124


      # - id: spatialde2
      #   name: "SpatialDE2"
      #   software_environment: "spatialde2"
      #   repository:
      #     url: https://github.com/A-meara/spatially_variable_genes/methods/spatialde2
      #     commit: 2f93124


    ## Methods consume data stage outputs
    inputs:
      - entries:
          - data.dataset
          - data.solution  # Needed for control methods

    ## Methods stage outputs
    outputs:
      - id: methods.predictions
        path: "{input}/{stage}/{module}/{params}/{dataset}.predictions.h5ad"

  ## Metrics stage - evaluate predictions
  - id: metrics
    modules:
      - id: correlation
        name: "Kendall Correlation"
        software_environment: "correlation"
        repository:
          url: https://github.com/A-meara/spatially_variable_genes
          commit: 2f93124
        parameters:
          - values: ["--component", "metrics/correlation"]

    ## Metrics consume method predictions and ground truth
    inputs:
      - entries:
          - methods.predictions
          - data.solution

    ## Metrics stage outputs
    outputs:
      - id: metrics.scores
        path: "{input}/{stage}/{module}/{params}/{dataset}.scores.h5ad"
